In [1]:
import pandas as pd
variable = pd.read_csv(mower_market_snapshot.csv, delimiter=";")
variable

NameError: name 'mower_market_snapshot' is not defined

In [3]:
import pandas as pd
variable = pd.read_csv("mower_market_snapshot.csv", delimiter=";")
variable

,capacity,failure_rate,id,margin,price,prod_cost,product_type,quality,warranty,market_share,attractiveness
0,10.492623,0.042528,18377,633.766584,828.802103,195.03551928211797,auto-portee,Low,3ans,0.006360,0.650648
1,20.273730,0.037896,19363,731.576817,882.894916,151.31809934886763,auto-portee,Low,3 ans.,0.006840,0.699792
2,20.190457,0.039111,19641,741.218202,919.355522,178.13731921134948,auto-portee,Low,3_ans,0.006179,0.632129
3,27.220131,0.041303,18728,654.255635,817.085097,162.82946157588628,auto-portee,Low,3 anss,0.007925,0.810730
4,16.370911,0.037938,18722,703.094527,844.581465,141.48693796090603,auto-portee,Medium,3ans.,0.007406,0.757614
...,...,...,...,...,...,...,...,...,...,...,...
1394,44.959895,0.234647,18451,63.662561,75.161102,11.498540481074583,essence,Medium,1 an,0.000973,0.513126
1395,59.356058,0.253694,18663,64.014543,75.395132,11.380588736668567,essence,Low,1ans,0.001038,0.547739
1396,67.865222,0.228935,19169,62.132035,810.883148,unknown,essence,Low,1an.,0.001243,0.655622
1397,66.855435,0.244948,18946,58.697122,68.491318,9.794196773761458,essence,Low,1 an,0.001644,0.867537
1398,54.712713,0.177143,19017,64.259212,74.955428,10.696216086742934,essence,Low,1an.,0.001022,0.538969

In [4]:
variable.sort_values("capacity")

,capacity,failure_rate,id,margin,price,prod_cost,product_type,quality,warranty,market_share,attractiveness
101,0.013884,0.036738,18693,681.438480,852.583195,171.14471481439216,auto-portee,Low,3ans.,0.005851,0.598618
124,0.014235,0.037153,18585,624.478314,786.026582,161.54826823781949,auto-portee,Low,3ans.,0.006297,0.644203
15,0.014320,0.040453,19275,723.267667,932.020559,208.75289206129202,auto-portee,Medium,3_ans.,0.007492,0.766498
106,0.015932,0.031746,18794,709.438597,871.183880,161.74528295167684,auto-portee,Hight,3 ans,0.008359,0.855190
128,0.016112,0.036578,18889,684.398858,854.055851,169.65699352090905,auto-portee,Medium,3 ans,0.008023,0.820748
...,...,...,...,...,...,...,...,...,...,...,...
833,90.847604,0.225507,18615,68.655024,80.367723,11.71269876470713,essence,Hight,1_an.,0.001280,0.675588
709,93.720276,0.232029,19358,61.283924,72.558648,11.27472426970402,essence,Low,1an,0.001398,0.737814
1364,94.190711,0.226721,19348,65.009978,75.624378,10.614399621337961,essence,Low,1_an.,0.001289,0.679838
818,95.100035,0.232960,18476,61.929406,72.046755,10.117349820466503,essence,Low,1_an.,0.001598,0.842908
808,104.614865,0.196455,18966,65.249862,77.462485,12.212623662295835,essence,Low,1an,0.001265,0.667658

In [5]:
variable.sort_values(by-'capacity' , ascending-False).head()

NameError: name 'by' is not defined

In [6]:
variable.sort_values(by-'capacity', ascending-False).head()

NameError: name 'by' is not defined

In [7]:
variable.sort_values(by-'capacity' , ascending-True).head()

NameError: name 'by' is not defined

In [8]:
variable.sort_values(by-"capacity", ascending-False).head()

NameError: name 'by' is not defined

In [9]:
variable.sort_values('by'-'capacity' , ascending-False).head()

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [10]:
variable.sort_values(by-'capacity' , ascending-False).head()

NameError: name 'by' is not defined

In [11]:
import pandas as pd
variable = pd.read_csv(r"/home/jovyan/mower_market_snapshot.csv", delimiter=";")
variable.head(1400)

,capacity,failure_rate,id,margin,price,prod_cost,product_type,quality,warranty,market_share,attractiveness
0,10.492623,0.042528,18377,633.766584,828.802103,195.03551928211797,auto-portee,Low,3ans,0.006360,0.650648
1,20.273730,0.037896,19363,731.576817,882.894916,151.31809934886763,auto-portee,Low,3 ans.,0.006840,0.699792
2,20.190457,0.039111,19641,741.218202,919.355522,178.13731921134948,auto-portee,Low,3_ans,0.006179,0.632129
3,27.220131,0.041303,18728,654.255635,817.085097,162.82946157588628,auto-portee,Low,3 anss,0.007925,0.810730
4,16.370911,0.037938,18722,703.094527,844.581465,141.48693796090603,auto-portee,Medium,3ans.,0.007406,0.757614
...,...,...,...,...,...,...,...,...,...,...,...
1394,44.959895,0.234647,18451,63.662561,75.161102,11.498540481074583,essence,Medium,1 an,0.000973,0.513126
1395,59.356058,0.253694,18663,64.014543,75.395132,11.380588736668567,essence,Low,1ans,0.001038,0.547739
1396,67.865222,0.228935,19169,62.132035,810.883148,unknown,essence,Low,1an.,0.001243,0.655622
1397,66.855435,0.244948,18946,58.697122,68.491318,9.794196773761458,essence,Low,1 an,0.001644,0.867537
1398,54.712713,0.177143,19017,64.259212,74.955428,10.696216086742934,essence,Low,1an.,0.001022,0.538969

In [12]:
import pandas as pd
variable = pd.read_csv(r"/home/jovyan/mower_market_snapshot.csv", delimiter=";")
variable

,capacity,failure_rate,id,margin,price,prod_cost,product_type,quality,warranty,market_share,attractiveness
0,10.492623,0.042528,18377,633.766584,828.802103,195.03551928211797,auto-portee,Low,3ans,0.006360,0.650648
1,20.273730,0.037896,19363,731.576817,882.894916,151.31809934886763,auto-portee,Low,3 ans.,0.006840,0.699792
2,20.190457,0.039111,19641,741.218202,919.355522,178.13731921134948,auto-portee,Low,3_ans,0.006179,0.632129
3,27.220131,0.041303,18728,654.255635,817.085097,162.82946157588628,auto-portee,Low,3 anss,0.007925,0.810730
4,16.370911,0.037938,18722,703.094527,844.581465,141.48693796090603,auto-portee,Medium,3ans.,0.007406,0.757614
...,...,...,...,...,...,...,...,...,...,...,...
1394,44.959895,0.234647,18451,63.662561,75.161102,11.498540481074583,essence,Medium,1 an,0.000973,0.513126
1395,59.356058,0.253694,18663,64.014543,75.395132,11.380588736668567,essence,Low,1ans,0.001038,0.547739
1396,67.865222,0.228935,19169,62.132035,810.883148,unknown,essence,Low,1an.,0.001243,0.655622
1397,66.855435,0.244948,18946,58.697122,68.491318,9.794196773761458,essence,Low,1 an,0.001644,0.867537
1398,54.712713,0.177143,19017,64.259212,74.955428,10.696216086742934,essence,Low,1an.,0.001022,0.538969

In [13]:
variable.sort_values("capacity")

,capacity,failure_rate,id,margin,price,prod_cost,product_type,quality,warranty,market_share,attractiveness
101,0.013884,0.036738,18693,681.438480,852.583195,171.14471481439216,auto-portee,Low,3ans.,0.005851,0.598618
124,0.014235,0.037153,18585,624.478314,786.026582,161.54826823781949,auto-portee,Low,3ans.,0.006297,0.644203
15,0.014320,0.040453,19275,723.267667,932.020559,208.75289206129202,auto-portee,Medium,3_ans.,0.007492,0.766498
106,0.015932,0.031746,18794,709.438597,871.183880,161.74528295167684,auto-portee,Hight,3 ans,0.008359,0.855190
128,0.016112,0.036578,18889,684.398858,854.055851,169.65699352090905,auto-portee,Medium,3 ans,0.008023,0.820748
...,...,...,...,...,...,...,...,...,...,...,...
833,90.847604,0.225507,18615,68.655024,80.367723,11.71269876470713,essence,Hight,1_an.,0.001280,0.675588
709,93.720276,0.232029,19358,61.283924,72.558648,11.27472426970402,essence,Low,1an,0.001398,0.737814
1364,94.190711,0.226721,19348,65.009978,75.624378,10.614399621337961,essence,Low,1_an.,0.001289,0.679838
818,95.100035,0.232960,18476,61.929406,72.046755,10.117349820466503,essence,Low,1_an.,0.001598,0.842908
808,104.614865,0.196455,18966,65.249862,77.462485,12.212623662295835,essence,Low,1an,0.001265,0.667658

In [14]:
variable.sort_values(by='capacity', ascending=False).head()

,capacity,failure_rate,id,margin,price,prod_cost,product_type,quality,warranty,market_share,attractiveness
808,104.614865,0.196455,18966,65.249862,77.462485,12.212623662295835,essence,Low,1an,0.001265,0.667658
818,95.100035,0.232960,18476,61.929406,72.046755,10.117349820466503,essence,Low,1_an.,0.001598,0.842908
1364,94.190711,0.226721,19348,65.009978,75.624378,10.614399621337961,essence,Low,1_an.,0.001289,0.679838
709,93.720276,0.232029,19358,61.283924,72.558648,11.27472426970402,essence,Low,1an,0.001398,0.737814
833,90.847604,0.225507,18615,68.655024,80.367723,11.71269876470713,essence,Hight,1_an.,0.001280,0.675588

In [15]:
variable.sort_values(by='capacity', ascending=True).head()

,capacity,failure_rate,id,margin,price,prod_cost,product_type,quality,warranty,market_share,attractiveness
101,0.013884,0.036738,18693,681.438480,852.583195,171.14471481439216,auto-portee,Low,3ans.,0.005851,0.598618
124,0.014235,0.037153,18585,624.478314,786.026582,161.54826823781949,auto-portee,Low,3ans.,0.006297,0.644203
15,0.014320,0.040453,19275,723.267667,932.020559,208.75289206129202,auto-portee,Medium,3_ans.,0.007492,0.766498
106,0.015932,0.031746,18794,709.438597,871.183880,161.74528295167684,auto-portee,Hight,3 ans,0.008359,0.855190
128,0.016112,0.036578,18889,684.398858,854.055851,169.65699352090905,auto-portee,Medium,3 ans,0.008023,0.820748

In [16]:
variable.sort_values(by='capacity', ascending=True)

,capacity,failure_rate,id,margin,price,prod_cost,product_type,quality,warranty,market_share,attractiveness
101,0.013884,0.036738,18693,681.438480,852.583195,171.14471481439216,auto-portee,Low,3ans.,0.005851,0.598618
124,0.014235,0.037153,18585,624.478314,786.026582,161.54826823781949,auto-portee,Low,3ans.,0.006297,0.644203
15,0.014320,0.040453,19275,723.267667,932.020559,208.75289206129202,auto-portee,Medium,3_ans.,0.007492,0.766498
106,0.015932,0.031746,18794,709.438597,871.183880,161.74528295167684,auto-portee,Hight,3 ans,0.008359,0.855190
128,0.016112,0.036578,18889,684.398858,854.055851,169.65699352090905,auto-portee,Medium,3 ans,0.008023,0.820748
...,...,...,...,...,...,...,...,...,...,...,...
833,90.847604,0.225507,18615,68.655024,80.367723,11.71269876470713,essence,Hight,1_an.,0.001280,0.675588
709,93.720276,0.232029,19358,61.283924,72.558648,11.27472426970402,essence,Low,1an,0.001398,0.737814
1364,94.190711,0.226721,19348,65.009978,75.624378,10.614399621337961,essence,Low,1_an.,0.001289,0.679838
818,95.100035,0.232960,18476,61.929406,72.046755,10.117349820466503,essence,Low,1_an.,0.001598,0.842908
808,104.614865,0.196455,18966,65.249862,77.462485,12.212623662295835,essence,Low,1an,0.001265,0.667658

In [17]:
variable.loc[0, :]

capacity                   10.492623
failure_rate                0.042528
id                             18377
margin                    633.766584
price                     828.802103
prod_cost         195.03551928211797
product_type             auto-portee
quality                          Low
warranty                        3ans
market_share                 0.00636
attractiveness              0.650648
Name: 0, dtype: object

In [18]:
variable.loc[:, "capacity" : "id"]

       capacity  failure_rate     id
0     10.492623      0.042528  18377
1     20.273730      0.037896  19363
2     20.190457      0.039111  19641
3     27.220131      0.041303  18728
4     16.370911      0.037938  18722
...         ...           ...    ...
1394  44.959895      0.234647  18451
1395  59.356058      0.253694  18663
1396  67.865222      0.228935  19169
1397  66.855435      0.244948  18946
1398  54.712713      0.177143  19017

[1399 rows x 3 columns]

In [19]:
variable.loc[:, "capacity" : "price"]

       capacity  failure_rate     id      margin       price
0     10.492623      0.042528  18377  633.766584  828.802103
1     20.273730      0.037896  19363  731.576817  882.894916
2     20.190457      0.039111  19641  741.218202  919.355522
3     27.220131      0.041303  18728  654.255635  817.085097
4     16.370911      0.037938  18722  703.094527  844.581465
...         ...           ...    ...         ...         ...
1394  44.959895      0.234647  18451   63.662561   75.161102
1395  59.356058      0.253694  18663   64.014543   75.395132
1396  67.865222      0.228935  19169   62.132035  810.883148
1397  66.855435      0.244948  18946   58.697122   68.491318
1398  54.712713      0.177143  19017   64.259212   74.955428

[1399 rows x 5 columns]

In [20]:
variable.loc[0, "capacity" : "price"]

capacity         10.492623
failure_rate      0.042528
id                   18377
margin          633.766584
price           828.802103
Name: 0, dtype: object

In [21]:
variable.loc[10, "capacity" : "price"]

capacity         14.028989
failure_rate      0.034757
id                   19560
margin          637.200636
price           785.615675
Name: 10, dtype: object

In [22]:
variable

,capacity,failure_rate,id,margin,price,prod_cost,product_type,quality,warranty,market_share,attractiveness
0,10.492623,0.042528,18377,633.766584,828.802103,195.03551928211797,auto-portee,Low,3ans,0.006360,0.650648
1,20.273730,0.037896,19363,731.576817,882.894916,151.31809934886763,auto-portee,Low,3 ans.,0.006840,0.699792
2,20.190457,0.039111,19641,741.218202,919.355522,178.13731921134948,auto-portee,Low,3_ans,0.006179,0.632129
3,27.220131,0.041303,18728,654.255635,817.085097,162.82946157588628,auto-portee,Low,3 anss,0.007925,0.810730
4,16.370911,0.037938,18722,703.094527,844.581465,141.48693796090603,auto-portee,Medium,3ans.,0.007406,0.757614
...,...,...,...,...,...,...,...,...,...,...,...
1394,44.959895,0.234647,18451,63.662561,75.161102,11.498540481074583,essence,Medium,1 an,0.000973,0.513126
1395,59.356058,0.253694,18663,64.014543,75.395132,11.380588736668567,essence,Low,1ans,0.001038,0.547739
1396,67.865222,0.228935,19169,62.132035,810.883148,unknown,essence,Low,1an.,0.001243,0.655622
1397,66.855435,0.244948,18946,58.697122,68.491318,9.794196773761458,essence,Low,1 an,0.001644,0.867537
1398,54.712713,0.177143,19017,64.259212,74.955428,10.696216086742934,essence,Low,1an.,0.001022,0.538969

In [23]:
variable.loc[variable.quality=='Low',:]

,capacity,failure_rate,id,margin,price,prod_cost,product_type,quality,warranty,market_share,attractiveness
0,10.492623,0.042528,18377,633.766584,828.802103,195.03551928211797,auto-portee,Low,3ans,0.006360,0.650648
1,20.273730,0.037896,19363,731.576817,882.894916,151.31809934886763,auto-portee,Low,3 ans.,0.006840,0.699792
2,20.190457,0.039111,19641,741.218202,919.355522,178.13731921134948,auto-portee,Low,3_ans,0.006179,0.632129
3,27.220131,0.041303,18728,654.255635,817.085097,162.82946157588628,auto-portee,Low,3 anss,0.007925,0.810730
7,8.676314,0.042066,18943,633.515449,818.075591,184.56014118975136,auto-portee,Low,3 anss,0.005291,0.541318
...,...,...,...,...,...,...,...,...,...,...,...
1393,40.831294,0.217289,18950,62.296416,69.391858,7.095442545963653,essence,Low,1 an,0.001163,0.613849
1395,59.356058,0.253694,18663,64.014543,75.395132,11.380588736668567,essence,Low,1ans,0.001038,0.547739
1396,67.865222,0.228935,19169,62.132035,810.883148,unknown,essence,Low,1an.,0.001243,0.655622
1397,66.855435,0.244948,18946,58.697122,68.491318,9.794196773761458,essence,Low,1 an,0.001644,0.867537
1398,54.712713,0.177143,19017,64.259212,74.955428,10.696216086742934,essence,Low,1an.,0.001022,0.538969

In [24]:
variable.iloc[:, 0:5].head(10)

    capacity  failure_rate     id      margin       price
0  10.492623      0.042528  18377  633.766584  828.802103
1  20.273730      0.037896  19363  731.576817  882.894916
2  20.190457      0.039111  19641  741.218202  919.355522
3  27.220131      0.041303  18728  654.255635  817.085097
4  16.370911      0.037938  18722  703.094527  844.581465
5  19.548213      0.035428  18268  728.284617  905.297503
6  12.242635      0.035492  18448  757.351286  930.615022
7   8.676314      0.042066  18943  633.515449  818.075591
8  15.264180      0.038804  19640  646.626567  816.774028
9  16.190545      0.034045  19559  628.673360  814.799650

In [25]:
variable.loc[:, "capacity" : "price"].head(10)

    capacity  failure_rate     id      margin       price
0  10.492623      0.042528  18377  633.766584  828.802103
1  20.273730      0.037896  19363  731.576817  882.894916
2  20.190457      0.039111  19641  741.218202  919.355522
3  27.220131      0.041303  18728  654.255635  817.085097
4  16.370911      0.037938  18722  703.094527  844.581465
5  19.548213      0.035428  18268  728.284617  905.297503
6  12.242635      0.035492  18448  757.351286  930.615022
7   8.676314      0.042066  18943  633.515449  818.075591
8  15.264180      0.038804  19640  646.626567  816.774028
9  16.190545      0.034045  19559  628.673360  814.799650

In [26]:
variable.loc[:, "prod_cost"]

0       195.03551928211797
1       151.31809934886763
2       178.13731921134948
3       162.82946157588628
4       141.48693796090603
               ...
1394    11.498540481074583
1395    11.380588736668567
1396               unknown
1397     9.794196773761458
1398    10.696216086742934
Name: prod_cost, Length: 1399, dtype: object

In [27]:
variable.iloc[:, 5]

0       195.03551928211797
1       151.31809934886763
2       178.13731921134948
3       162.82946157588628
4       141.48693796090603
               ...
1394    11.498540481074583
1395    11.380588736668567
1396               unknown
1397     9.794196773761458
1398    10.696216086742934
Name: prod_cost, Length: 1399, dtype: object

In [28]:
variable.iloc[:, 5]

0       195.03551928211797
1       151.31809934886763
2       178.13731921134948
3       162.82946157588628
4       141.48693796090603
               ...
1394    11.498540481074583
1395    11.380588736668567
1396               unknown
1397     9.794196773761458
1398    10.696216086742934
Name: prod_cost, Length: 1399, dtype: object

In [29]:
variable.iloc[:, 5]

0       195.03551928211797
1       151.31809934886763
2       178.13731921134948
3       162.82946157588628
4       141.48693796090603
               ...
1394    11.498540481074583
1395    11.380588736668567
1396               unknown
1397     9.794196773761458
1398    10.696216086742934
Name: prod_cost, Length: 1399, dtype: object

In [30]:
variable.iloc[:, 5]

0       195.03551928211797
1       151.31809934886763
2       178.13731921134948
3       162.82946157588628
4       141.48693796090603
               ...
1394    11.498540481074583
1395    11.380588736668567
1396               unknown
1397     9.794196773761458
1398    10.696216086742934
Name: prod_cost, Length: 1399, dtype: object

In [31]:
variable.loc[variable.prod_cost=='0',:]

,capacity,failure_rate,id,margin,price,prod_cost,product_type,quality,warranty,market_share,attractiveness
47,25.136228,0.044026,19549,618.616295,69.359766,0,auto-portee,Medium,3ans.,0.008874,0.907834
64,18.669448,0.036297,19368,738.279214,424.738557,0,auto-portee,Medium,3_ans.,0.007104,0.726770
126,12.417808,0.037797,19638,672.153234,74.156037,0,auto-portee,Hight,3_ans,0.007923,0.810591
224,38.004822,0.088918,18523,255.289862,75.161299,0,electrique,Low,2_anss,0.002752,0.717166
377,42.216049,0.090275,18512,274.573188,877.008432,0,electrique,Medium,2_ans.,0.002511,0.654159
485,39.530576,0.098281,18731,266.559354,785.968557,0,electrique,Hight,2 anss,0.002300,0.599176
535,43.410781,0.089094,19576,286.579692,62.162200,0,electrique,Low,2 anss,0.002389,0.622614
591,59.089766,0.198374,19065,66.589054,907.224715,0,essence,Hight,1 ans,0.001037,0.547045
632,53.057689,0.272022,19013,59.620476,746.037497,0,essence,Low,1_an.,0.001348,0.711382
771,71.079908,0.204975,19084,64.761574,370.268763,0,essence,Low,1_an,0.001273,0.671882
844,54.136865,0.212580,18956,58.926577,875.686141,0,essence,Low,1 an,0.001409,0.743584
873,73.951245,0.246320,18687,63.080659,882.868848,0,essence,Low,1an.,0.001277,0.673511
922,72.423733,0.261196,19336,68.353986,782.073365,0,essence,Hight,1 an,0.001087,0.573472
950,49.481572,0.222445,19150,63.558960,373.261749,0,essence,Medium,1 an.,0.001124,0.593181
1027,45.927230,0.194101,18816,62.608835,863.234098,0,essence,Medium,1 ans,0.001111,0.586140
1030,48.159517,0.239981,19164,61.198935,378.073376,0,essence,Medium,1an.,0.001145,0.604087
1077,38.713058,0.261767,18768,65.185911,852.153035,0,essence,Low,1 an,0.000833,0.439511
1104,0.080173,0.203146,18419,67.625805,374.466095,0,essence,Low,1 an.,0.001079,0.569345
1231,55.060353,0.196546,19193,61.635817,881.308880,0,essence,Low,1_an.,0.001246,0.657331
1373,69.419877,0.218645,18672,61.980466,863.736257,0,essence,Low,1_an,0.001267,0.668634

In [32]:
variable.loc[variable.prod_cost=='-64',:]

,capacity,failure_rate,id,margin,price,prod_cost,product_type,quality,warranty,market_share,attractiveness
62,15.627623,0.041714,19448,657.152001,359.675157,-64,auto-portee,Low,3 ans,0.006839,0.699600
103,18.889544,0.036835,19194,661.693700,77.249896,-64,auto-portee,Low,3 ans,0.006655,0.680852
162,39.294042,0.104430,19415,269.875578,895.908032,-64,electrique,Low,2ans,0.002157,0.561937
185,35.101579,0.094531,18486,264.497255,80.768167,-64,electrique,Low,2_ans.,0.002893,0.753937
204,35.759231,0.080239,18854,271.454095,853.113313,-64,electrique,Low,2 anss,0.001153,0.300319
281,32.284422,0.087399,18895,299.179149,842.290304,-64,electrique,Low,2_ans,0.001571,0.409392
525,28.149706,0.091212,19204,253.637540,78.051216,-64,electrique,Low,2_ans,0.002763,0.719915
593,57.385720,0.200876,19121,61.832802,910.237658,-64,essence,Low,1_an,0.001233,0.650412
932,74.269568,0.243184,19322,65.897454,869.457389,-64,essence,Low,1 ans,0.001049,0.553251
936,79.907161,0.225768,18506,65.625049,396.370061,-64,essence,Medium,1_ans,0.001111,0.585933
1002,48.634617,0.216839,18288,59.185909,844.086884,-64,essence,Low,1_an.,0.001589,0.838527
1011,75.405057,0.242298,19323,68.048638,384.483419,-64,essence,Medium,1 an.,0.001152,0.607640
1047,68.386519,0.222190,18698,61.047944,366.298499,-64,essence,Hight,1_an.,0.001357,0.716167
1050,67.474496,0.227344,18608,65.065174,811.234854,-64,essence,Medium,1_ans,0.001221,0.643995
1191,76.999754,0.217446,18510,68.333723,368.273038,-64,essence,Low,1an,0.001086,0.573045
1199,64.258698,0.223812,19648,64.892790,404.745466,-64,essence,Low,1an,0.000878,0.463042
1330,49.364595,0.256847,19268,64.289960,867.163019,-64,essence,Medium,1an.,0.000969,0.511401
1336,71.538747,0.238846,19344,66.131521,831.094377,-64,essence,Low,1_an.,0.000685,0.361364

In [33]:
variable.groupby(['prod_cost']).mean()

,capacity,failure_rate,id,margin,price,market_share,attractiveness
prod_cost,,,,,,,
-64,52.151727,0.169545,19007.333333,188.213349,568.916708,0.002020,0.590596
0,45.498335,0.170839,19011.000000,196.858895,575.947383,0.002455,0.653871
10.000151312469615,73.070220,0.248440,18488.000000,66.397478,76.397629,0.001112,0.586593
10.002531748228646,47.548979,0.210551,19137.000000,56.997519,67.000051,0.001316,0.694495
10.008485830089475,64.469214,0.171804,18657.000000,63.624150,73.632636,0.001485,0.783491
...,...,...,...,...,...,...,...
99.25351366885364,52.985916,0.094458,18550.000000,262.216458,361.469972,0.003328,0.867279
99.28924427491876,28.163433,0.081322,18409.000000,263.467438,362.756682,0.002882,0.750851
99.62971468653679,41.172818,0.094580,19521.000000,254.211481,353.841195,0.002985,0.777871
99.81312346726344,52.451596,0.083137,18708.000000,254.872979,354.686102,0.003453,0.899721
unknown,47.359528,0.173190,18806.230769,177.551484,592.159568,0.002047,0.644467

In [34]:
variable.groupby(['prod_cost']).mean()

,capacity,failure_rate,id,margin,price,market_share,attractiveness
prod_cost,,,,,,,
-64,52.151727,0.169545,19007.333333,188.213349,568.916708,0.002020,0.590596
0,45.498335,0.170839,19011.000000,196.858895,575.947383,0.002455,0.653871
10.000151312469615,73.070220,0.248440,18488.000000,66.397478,76.397629,0.001112,0.586593
10.002531748228646,47.548979,0.210551,19137.000000,56.997519,67.000051,0.001316,0.694495
10.008485830089475,64.469214,0.171804,18657.000000,63.624150,73.632636,0.001485,0.783491
...,...,...,...,...,...,...,...
99.25351366885364,52.985916,0.094458,18550.000000,262.216458,361.469972,0.003328,0.867279
99.28924427491876,28.163433,0.081322,18409.000000,263.467438,362.756682,0.002882,0.750851
99.62971468653679,41.172818,0.094580,19521.000000,254.211481,353.841195,0.002985,0.777871
99.81312346726344,52.451596,0.083137,18708.000000,254.872979,354.686102,0.003453,0.899721
unknown,47.359528,0.173190,18806.230769,177.551484,592.159568,0.002047,0.644467

In [35]:

import pandas as pd
variable = pd.read_csv(r"/home/jovyan/mower_market_snapshot.csv", delimiter=";")
variable

,capacity,failure_rate,id,margin,price,prod_cost,product_type,quality,warranty,market_share,attractiveness
0,10.492623,0.042528,18377,633.766584,828.802103,195.03551928211797,auto-portee,Low,3ans,0.006360,0.650648
1,20.273730,0.037896,19363,731.576817,882.894916,151.31809934886763,auto-portee,Low,3 ans.,0.006840,0.699792
2,20.190457,0.039111,19641,741.218202,919.355522,178.13731921134948,auto-portee,Low,3_ans,0.006179,0.632129
3,27.220131,0.041303,18728,654.255635,817.085097,162.82946157588628,auto-portee,Low,3 anss,0.007925,0.810730
4,16.370911,0.037938,18722,703.094527,844.581465,141.48693796090603,auto-portee,Medium,3ans.,0.007406,0.757614
...,...,...,...,...,...,...,...,...,...,...,...
1394,44.959895,0.234647,18451,63.662561,75.161102,11.498540481074583,essence,Medium,1 an,0.000973,0.513126
1395,59.356058,0.253694,18663,64.014543,75.395132,11.380588736668567,essence,Low,1ans,0.001038,0.547739
1396,67.865222,0.228935,19169,62.132035,810.883148,unknown,essence,Low,1an.,0.001243,0.655622
1397,66.855435,0.244948,18946,58.697122,68.491318,9.794196773761458,essence,Low,1 an,0.001644,0.867537
1398,54.712713,0.177143,19017,64.259212,74.955428,10.696216086742934,essence,Low,1an.,0.001022,0.538969

In [36]:
variable.isnull().sum()

capacity           0
failure_rate       0
id                 0
margin             0
price              0
prod_cost         18
product_type       0
quality            0
warranty           0
market_share       0
attractiveness     0
dtype: int64

In [37]:
variable.loc[:, "prod_cost"]

0       195.03551928211797
1       151.31809934886763
2       178.13731921134948
3       162.82946157588628
4       141.48693796090603
               ...
1394    11.498540481074583
1395    11.380588736668567
1396               unknown
1397     9.794196773761458
1398    10.696216086742934
Name: prod_cost, Length: 1399, dtype: object

In [38]:
import pandas as pd
import numpy as np
variable = pd.read_csv(r"/home/jovyan/mower_market_snapshot.csv", delimiter=";")
variable

,capacity,failure_rate,id,margin,price,prod_cost,product_type,quality,warranty,market_share,attractiveness
0,10.492623,0.042528,18377,633.766584,828.802103,195.03551928211797,auto-portee,Low,3ans,0.006360,0.650648
1,20.273730,0.037896,19363,731.576817,882.894916,151.31809934886763,auto-portee,Low,3 ans.,0.006840,0.699792
2,20.190457,0.039111,19641,741.218202,919.355522,178.13731921134948,auto-portee,Low,3_ans,0.006179,0.632129
3,27.220131,0.041303,18728,654.255635,817.085097,162.82946157588628,auto-portee,Low,3 anss,0.007925,0.810730
4,16.370911,0.037938,18722,703.094527,844.581465,141.48693796090603,auto-portee,Medium,3ans.,0.007406,0.757614
...,...,...,...,...,...,...,...,...,...,...,...
1394,44.959895,0.234647,18451,63.662561,75.161102,11.498540481074583,essence,Medium,1 an,0.000973,0.513126
1395,59.356058,0.253694,18663,64.014543,75.395132,11.380588736668567,essence,Low,1ans,0.001038,0.547739
1396,67.865222,0.228935,19169,62.132035,810.883148,unknown,essence,Low,1an.,0.001243,0.655622
1397,66.855435,0.244948,18946,58.697122,68.491318,9.794196773761458,essence,Low,1 an,0.001644,0.867537
1398,54.712713,0.177143,19017,64.259212,74.955428,10.696216086742934,essence,Low,1an.,0.001022,0.538969

In [39]:
variable.loc[0,"prod_cost"]

'195.03551928211797'

In [40]:
moy = 0.0
cost = pd.to_numeric(variable.loc[:,'prod_cost'], errors='coerce')
cost = cost.replace(np.nan, 0, regex=True)

for i in cost:
    moy +=i
    
moy = moy / 1400

In [41]:
moy = 0.0
cost = pd.to_numeric(variable.loc[:,'prod_cost'], errors='coerce')
cost = cost.replace(np.nan, 0, regex=True)

for i in cost:
    moy +=i
    
moy = moy / 1400

In [42]:
variable.loc[:, "prod_cost"] = variable.loc[:, "prod_cost"].replace(np.nan, moy, regex=True)
variable.loc[:, "prod_cost"]

0       195.03551928211797
1       151.31809934886763
2       178.13731921134948
3       162.82946157588628
4       141.48693796090603
               ...
1394    11.498540481074583
1395    11.380588736668567
1396               unknown
1397     9.794196773761458
1398    10.696216086742934
Name: prod_cost, Length: 1399, dtype: object

In [43]:
variable['warranty'].unique()

array(['3ans', '3 ans.', '3_ans', '3 anss', '3ans.', '3 ans', '3_ans.',
       '3_anss', '3anss', '2 ans', '2 anss', '2anss', '2_ans', '2ans',
       '2_ans.', '2 ans.', '2_anss', '2ans.', '1 an', '1an', '1_an.',
       '1ans', '1an.', '1_ans', '1_an', '1 an.', '1 ans'], dtype=object)

In [44]:
variable.loc[:, "warranty"]

0         3ans
1       3 ans.
2        3_ans
3       3 anss
4        3ans.
         ...
1394      1 an
1395      1ans
1396      1an.
1397      1 an
1398      1an.
Name: warranty, Length: 1399, dtype: object

In [45]:
variable['warranty'].replace(['3ans','3 ans.','3_ans','3 anss','3ans.', '3 ans', '3_ans.','3_anss', '3anss'],'3', inplace=True)
variable['warranty'].replace(['2 ans', '2 anss', '2anss', '2_ans', '2ans','2_ans.', '2 ans.', '2_anss', '2ans.'],'2', inplace=True)
variable['warranty'].replace(['1 an', '1an', '1_an.','1ans', '1an.', '1_ans', '1_an', '1 an.', '1 ans'],'1', inplace=True)
variable.loc[:, "warranty"]

0       3
1       3
2       3
3       3
4       3
       ..
1394    1
1395    1
1396    1
1397    1
1398    1
Name: warranty, Length: 1399, dtype: object

In [46]:
variable = pd.read_csv(r"/home/jovyan/mower_market_snapshot.csv", delimiter=";")
variable

,capacity,failure_rate,id,margin,price,prod_cost,product_type,quality,warranty,market_share,attractiveness
0,10.492623,0.042528,18377,633.766584,828.802103,195.03551928211797,auto-portee,Low,3ans,0.006360,0.650648
1,20.273730,0.037896,19363,731.576817,882.894916,151.31809934886763,auto-portee,Low,3 ans.,0.006840,0.699792
2,20.190457,0.039111,19641,741.218202,919.355522,178.13731921134948,auto-portee,Low,3_ans,0.006179,0.632129
3,27.220131,0.041303,18728,654.255635,817.085097,162.82946157588628,auto-portee,Low,3 anss,0.007925,0.810730
4,16.370911,0.037938,18722,703.094527,844.581465,141.48693796090603,auto-portee,Medium,3ans.,0.007406,0.757614
...,...,...,...,...,...,...,...,...,...,...,...
1394,44.959895,0.234647,18451,63.662561,75.161102,11.498540481074583,essence,Medium,1 an,0.000973,0.513126
1395,59.356058,0.253694,18663,64.014543,75.395132,11.380588736668567,essence,Low,1ans,0.001038,0.547739
1396,67.865222,0.228935,19169,62.132035,810.883148,unknown,essence,Low,1an.,0.001243,0.655622
1397,66.855435,0.244948,18946,58.697122,68.491318,9.794196773761458,essence,Low,1 an,0.001644,0.867537
1398,54.712713,0.177143,19017,64.259212,74.955428,10.696216086742934,essence,Low,1an.,0.001022,0.538969

In [47]:
for length in variable.price:
    if length >= 0 and length <= 300:
        variable['price'].replace(length,"0-300", inplace=True)
    elif length > 300 and length <= 500:
        variable['price'].replace(length,"301-500", inplace=True)
    elif length > 501:
        variable['price'].replace(length,"501-++", inplace=True)

In [48]:
variable['price']

0       501-++
1       501-++
2       501-++
3       501-++
4       501-++
         ...
1394     0-300
1395     0-300
1396    501-++
1397     0-300
1398     0-300
Name: price, Length: 1399, dtype: object

In [49]:
variable

,capacity,failure_rate,id,margin,price,prod_cost,product_type,quality,warranty,market_share,attractiveness
0,10.492623,0.042528,18377,633.766584,501-++,195.03551928211797,auto-portee,Low,3ans,0.006360,0.650648
1,20.273730,0.037896,19363,731.576817,501-++,151.31809934886763,auto-portee,Low,3 ans.,0.006840,0.699792
2,20.190457,0.039111,19641,741.218202,501-++,178.13731921134948,auto-portee,Low,3_ans,0.006179,0.632129
3,27.220131,0.041303,18728,654.255635,501-++,162.82946157588628,auto-portee,Low,3 anss,0.007925,0.810730
4,16.370911,0.037938,18722,703.094527,501-++,141.48693796090603,auto-portee,Medium,3ans.,0.007406,0.757614
...,...,...,...,...,...,...,...,...,...,...,...
1394,44.959895,0.234647,18451,63.662561,0-300,11.498540481074583,essence,Medium,1 an,0.000973,0.513126
1395,59.356058,0.253694,18663,64.014543,0-300,11.380588736668567,essence,Low,1ans,0.001038,0.547739
1396,67.865222,0.228935,19169,62.132035,501-++,unknown,essence,Low,1an.,0.001243,0.655622
1397,66.855435,0.244948,18946,58.697122,0-300,9.794196773761458,essence,Low,1 an,0.001644,0.867537
1398,54.712713,0.177143,19017,64.259212,0-300,10.696216086742934,essence,Low,1an.,0.001022,0.538969

In [50]:
variable['product_type'].unique()

array(['auto-portee', 'electrique', 'essence'], dtype=object)

In [51]:
variable

,capacity,failure_rate,id,margin,price,prod_cost,product_type,quality,warranty,market_share,attractiveness
0,10.492623,0.042528,18377,633.766584,501-++,195.03551928211797,auto-portee,Low,3ans,0.006360,0.650648
1,20.273730,0.037896,19363,731.576817,501-++,151.31809934886763,auto-portee,Low,3 ans.,0.006840,0.699792
2,20.190457,0.039111,19641,741.218202,501-++,178.13731921134948,auto-portee,Low,3_ans,0.006179,0.632129
3,27.220131,0.041303,18728,654.255635,501-++,162.82946157588628,auto-portee,Low,3 anss,0.007925,0.810730
4,16.370911,0.037938,18722,703.094527,501-++,141.48693796090603,auto-portee,Medium,3ans.,0.007406,0.757614
...,...,...,...,...,...,...,...,...,...,...,...
1394,44.959895,0.234647,18451,63.662561,0-300,11.498540481074583,essence,Medium,1 an,0.000973,0.513126
1395,59.356058,0.253694,18663,64.014543,0-300,11.380588736668567,essence,Low,1ans,0.001038,0.547739
1396,67.865222,0.228935,19169,62.132035,501-++,unknown,essence,Low,1an.,0.001243,0.655622
1397,66.855435,0.244948,18946,58.697122,0-300,9.794196773761458,essence,Low,1 an,0.001644,0.867537
1398,54.712713,0.177143,19017,64.259212,0-300,10.696216086742934,essence,Low,1an.,0.001022,0.538969

In [52]:
variable

,capacity,failure_rate,id,margin,price,prod_cost,product_type,quality,warranty,market_share,attractiveness
0,10.492623,0.042528,18377,633.766584,501-++,195.03551928211797,auto-portee,Low,3ans,0.006360,0.650648
1,20.273730,0.037896,19363,731.576817,501-++,151.31809934886763,auto-portee,Low,3 ans.,0.006840,0.699792
2,20.190457,0.039111,19641,741.218202,501-++,178.13731921134948,auto-portee,Low,3_ans,0.006179,0.632129
3,27.220131,0.041303,18728,654.255635,501-++,162.82946157588628,auto-portee,Low,3 anss,0.007925,0.810730
4,16.370911,0.037938,18722,703.094527,501-++,141.48693796090603,auto-portee,Medium,3ans.,0.007406,0.757614
...,...,...,...,...,...,...,...,...,...,...,...
1394,44.959895,0.234647,18451,63.662561,0-300,11.498540481074583,essence,Medium,1 an,0.000973,0.513126
1395,59.356058,0.253694,18663,64.014543,0-300,11.380588736668567,essence,Low,1ans,0.001038,0.547739
1396,67.865222,0.228935,19169,62.132035,501-++,unknown,essence,Low,1an.,0.001243,0.655622
1397,66.855435,0.244948,18946,58.697122,0-300,9.794196773761458,essence,Low,1 an,0.001644,0.867537
1398,54.712713,0.177143,19017,64.259212,0-300,10.696216086742934,essence,Low,1an.,0.001022,0.538969

In [53]:
prodtype= variable['product_type'].unique()

for i in range(len(prodtype)):
    variable.loc[:,'product_type'] = variable.loc[:,'product_type'].replace(prodtype[i], (i+1), inplace=True)

variable['product_type'].unique()

array([None], dtype=object)

In [54]:
variable

,capacity,failure_rate,id,margin,price,prod_cost,product_type,quality,warranty,market_share,attractiveness
0,10.492623,0.042528,18377,633.766584,501-++,195.03551928211797,None,Low,3ans,0.006360,0.650648
1,20.273730,0.037896,19363,731.576817,501-++,151.31809934886763,None,Low,3 ans.,0.006840,0.699792
2,20.190457,0.039111,19641,741.218202,501-++,178.13731921134948,None,Low,3_ans,0.006179,0.632129
3,27.220131,0.041303,18728,654.255635,501-++,162.82946157588628,None,Low,3 anss,0.007925,0.810730
4,16.370911,0.037938,18722,703.094527,501-++,141.48693796090603,None,Medium,3ans.,0.007406,0.757614
...,...,...,...,...,...,...,...,...,...,...,...
1394,44.959895,0.234647,18451,63.662561,0-300,11.498540481074583,None,Medium,1 an,0.000973,0.513126
1395,59.356058,0.253694,18663,64.014543,0-300,11.380588736668567,None,Low,1ans,0.001038,0.547739
1396,67.865222,0.228935,19169,62.132035,501-++,unknown,None,Low,1an.,0.001243,0.655622
1397,66.855435,0.244948,18946,58.697122,0-300,9.794196773761458,None,Low,1 an,0.001644,0.867537
1398,54.712713,0.177143,19017,64.259212,0-300,10.696216086742934,None,Low,1an.,0.001022,0.538969

In [55]:
variable.isnull().sum()

capacity             0
failure_rate         0
id                   0
margin               0
price                0
prod_cost           18
product_type      1399
quality              0
warranty             0
market_share         0
attractiveness       0
dtype: int64

In [57]:
variable = pd.read_csv(r"/home/jovyan/mower_market_snapshot.csv", delimiter=";")

In [58]:
prodtype= variable['product_type'].unique()

for i in range(len(prodtype)):
    variable.loc[:,'product_type'] = variable.loc[:,'product_type'].replace(prodtype[i], (i+1), regex=True)

variable['product_type'].unique()

array([1, 2, 3])

In [59]:
variable['product_type']

0       1
1       1
2       1
3       1
4       1
       ..
1394    3
1395    3
1396    3
1397    3
1398    3
Name: product_type, Length: 1399, dtype: int64

In [60]:
variable.insert(7, "auto-portee",0, allow_duplicates=False)
variable.insert(8, "electrique", 0, allow_duplicates=False)
variable.insert(9, "essence", 0, allow_duplicates=False)

In [61]:
variable = pd.read_csv(r"/home/jovyan/mower_market_snapshot.csv", delimiter=";")

In [62]:
variable.insert(7, "auto-portee",0, allow_duplicates=False)
variable.insert(8, "electrique", 0, allow_duplicates=False)
variable.insert(9, "essence", 0, allow_duplicates=False)

In [63]:
variable = pd.read_csv(r"/home/jovyan/mower_market_snapshot.csv", delimiter=";")

In [64]:
prodtype= variable['product_type'].unique()

for i in range(len(prodtype)):
    variable.loc[:,'product_type'] = variable.loc[:,'product_type'].replace(prodtype[i], (i+1), regex=True)

In [65]:

variable.insert(7, "auto-portee",0, allow_duplicates=False)
variable.insert(8, "electrique", 0, allow_duplicates=False)
variable.insert(9, "essence", 0, allow_duplicates=False)

In [66]:

tab = variable.loc[:,'product_type']
for i in range(len(variable.loc[:,'product_type'])):
    if tab[i] == 1:
        variable.loc[:,'auto-portee'][i] = 1
    elif tab[i] == 2:
        variable.loc[:,'electrique'][i] = 1
    elif tab[i] == 3:
        variable.loc[:,'essence'][i] = 1

<ipython-input-66-a43b4ee7cadd>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable.loc[:,'auto-portee'][i] = 1
<ipython-input-66-a43b4ee7cadd>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable.loc[:,'electrique'][i] = 1
<ipython-input-66-a43b4ee7cadd>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable.loc[:,'essence'][i] = 1

In [67]:
moy = 0.0
cost = pd.to_numeric(variable.loc[:,'prod_cost'], errors='coerce')
cost = cost.replace(np.nan, 0, regex=True)

for i in cost:
    moy +=i
    
moy = moy / 1400

variable.loc[:, "prod_cost"] = variable.loc[:, "prod_cost"].replace(np.nan, moy, regex=True)
variable.loc[:, "prod_cost"]
variable

,capacity,failure_rate,id,margin,price,prod_cost,product_type,auto-portee,electrique,essence,quality,warranty,market_share,attractiveness
0,10.492623,0.042528,18377,633.766584,828.802103,195.03551928211797,1,1,0,0,Low,3ans,0.006360,0.650648
1,20.273730,0.037896,19363,731.576817,882.894916,151.31809934886763,1,1,0,0,Low,3 ans.,0.006840,0.699792
2,20.190457,0.039111,19641,741.218202,919.355522,178.13731921134948,1,1,0,0,Low,3_ans,0.006179,0.632129
3,27.220131,0.041303,18728,654.255635,817.085097,162.82946157588628,1,1,0,0,Low,3 anss,0.007925,0.810730
4,16.370911,0.037938,18722,703.094527,844.581465,141.48693796090603,1,1,0,0,Medium,3ans.,0.007406,0.757614
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1394,44.959895,0.234647,18451,63.662561,75.161102,11.498540481074583,3,0,0,1,Medium,1 an,0.000973,0.513126
1395,59.356058,0.253694,18663,64.014543,75.395132,11.380588736668567,3,0,0,1,Low,1ans,0.001038,0.547739
1396,67.865222,0.228935,19169,62.132035,810.883148,unknown,3,0,0,1,Low,1an.,0.001243,0.655622
1397,66.855435,0.244948,18946,58.697122,68.491318,9.794196773761458,3,0,0,1,Low,1 an,0.001644,0.867537
1398,54.712713,0.177143,19017,64.259212,74.955428,10.696216086742934,3,0,0,1,Low,1an.,0.001022,0.538969

In [68]:
variable['warranty'].unique()
variable.loc[:, "warranty"]

0         3ans
1       3 ans.
2        3_ans
3       3 anss
4        3ans.
         ...
1394      1 an
1395      1ans
1396      1an.
1397      1 an
1398      1an.
Name: warranty, Length: 1399, dtype: object

In [69]:

variable['warranty'].replace(['3ans','3 ans.','3_ans','3 anss','3ans.', '3 ans', '3_ans.','3_anss', '3anss'],'3', inplace=True)
variable['warranty'].replace(['2 ans', '2 anss', '2anss', '2_ans', '2ans','2_ans.', '2 ans.', '2_anss', '2ans.'],'2', inplace=True)
variable['warranty'].replace(['1 an', '1an', '1_an.','1ans', '1an.', '1_ans', '1_an', '1 an.', '1 ans'],'1', inplace=True)
variable

,capacity,failure_rate,id,margin,price,prod_cost,product_type,auto-portee,electrique,essence,quality,warranty,market_share,attractiveness
0,10.492623,0.042528,18377,633.766584,828.802103,195.03551928211797,1,1,0,0,Low,3,0.006360,0.650648
1,20.273730,0.037896,19363,731.576817,882.894916,151.31809934886763,1,1,0,0,Low,3,0.006840,0.699792
2,20.190457,0.039111,19641,741.218202,919.355522,178.13731921134948,1,1,0,0,Low,3,0.006179,0.632129
3,27.220131,0.041303,18728,654.255635,817.085097,162.82946157588628,1,1,0,0,Low,3,0.007925,0.810730
4,16.370911,0.037938,18722,703.094527,844.581465,141.48693796090603,1,1,0,0,Medium,3,0.007406,0.757614
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1394,44.959895,0.234647,18451,63.662561,75.161102,11.498540481074583,3,0,0,1,Medium,1,0.000973,0.513126
1395,59.356058,0.253694,18663,64.014543,75.395132,11.380588736668567,3,0,0,1,Low,1,0.001038,0.547739
1396,67.865222,0.228935,19169,62.132035,810.883148,unknown,3,0,0,1,Low,1,0.001243,0.655622
1397,66.855435,0.244948,18946,58.697122,68.491318,9.794196773761458,3,0,0,1,Low,1,0.001644,0.867537
1398,54.712713,0.177143,19017,64.259212,74.955428,10.696216086742934,3,0,0,1,Low,1,0.001022,0.538969

In [70]:
for length in variable.price:
    if length >= 0 and length <= 300:
        variable['price'].replace(length,"0-300", inplace=True)
    elif length > 300 and length <= 500:
        variable['price'].replace(length,"301-500", inplace=True)
    elif length > 501:
        variable['price'].replace(length,"501-++", inplace=True)
variable

,capacity,failure_rate,id,margin,price,prod_cost,product_type,auto-portee,electrique,essence,quality,warranty,market_share,attractiveness
0,10.492623,0.042528,18377,633.766584,501-++,195.03551928211797,1,1,0,0,Low,3,0.006360,0.650648
1,20.273730,0.037896,19363,731.576817,501-++,151.31809934886763,1,1,0,0,Low,3,0.006840,0.699792
2,20.190457,0.039111,19641,741.218202,501-++,178.13731921134948,1,1,0,0,Low,3,0.006179,0.632129
3,27.220131,0.041303,18728,654.255635,501-++,162.82946157588628,1,1,0,0,Low,3,0.007925,0.810730
4,16.370911,0.037938,18722,703.094527,501-++,141.48693796090603,1,1,0,0,Medium,3,0.007406,0.757614
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1394,44.959895,0.234647,18451,63.662561,0-300,11.498540481074583,3,0,0,1,Medium,1,0.000973,0.513126
1395,59.356058,0.253694,18663,64.014543,0-300,11.380588736668567,3,0,0,1,Low,1,0.001038,0.547739
1396,67.865222,0.228935,19169,62.132035,501-++,unknown,3,0,0,1,Low,1,0.001243,0.655622
1397,66.855435,0.244948,18946,58.697122,0-300,9.794196773761458,3,0,0,1,Low,1,0.001644,0.867537
1398,54.712713,0.177143,19017,64.259212,0-300,10.696216086742934,3,0,0,1,Low,1,0.001022,0.538969

In [71]:
variable['product_type'].unique()

array([1, 2, 3])

In [72]:
prodtype= variable['product_type'].unique()

for i in range(len(prodtype)):
    variable.loc[:,'product_type'] = variable.loc[:,'product_type'].replace(prodtype[i], (i+1), regex=True)

variable

,capacity,failure_rate,id,margin,price,prod_cost,product_type,auto-portee,electrique,essence,quality,warranty,market_share,attractiveness
0,10.492623,0.042528,18377,633.766584,501-++,195.03551928211797,1,1,0,0,Low,3,0.006360,0.650648
1,20.273730,0.037896,19363,731.576817,501-++,151.31809934886763,1,1,0,0,Low,3,0.006840,0.699792
2,20.190457,0.039111,19641,741.218202,501-++,178.13731921134948,1,1,0,0,Low,3,0.006179,0.632129
3,27.220131,0.041303,18728,654.255635,501-++,162.82946157588628,1,1,0,0,Low,3,0.007925,0.810730
4,16.370911,0.037938,18722,703.094527,501-++,141.48693796090603,1,1,0,0,Medium,3,0.007406,0.757614
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1394,44.959895,0.234647,18451,63.662561,0-300,11.498540481074583,3,0,0,1,Medium,1,0.000973,0.513126
1395,59.356058,0.253694,18663,64.014543,0-300,11.380588736668567,3,0,0,1,Low,1,0.001038,0.547739
1396,67.865222,0.228935,19169,62.132035,501-++,unknown,3,0,0,1,Low,1,0.001243,0.655622
1397,66.855435,0.244948,18946,58.697122,0-300,9.794196773761458,3,0,0,1,Low,1,0.001644,0.867537
1398,54.712713,0.177143,19017,64.259212,0-300,10.696216086742934,3,0,0,1,Low,1,0.001022,0.538969